openapi: 3.2.0
info:
  title: HighBond API Reference Robot Apps API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robot Apps
  x-displayName: Analytic scripts
  description: 'An analytic script is a regular script with an analytic header. You can upload analytic scripts to a robot.


    The analytic header is a series of declarative tags that allow the script to run in the Robots app. The analytic header includes input parameters that a user populates in

    advance, which allows the analytic script to run unattended, either immediately, or at a scheduled time.


    Learn more about analytic scripts.'
paths:
  /orgs/{org_id}/robots/{robot_id}/robot_apps/{robot_app_id}:
    get:
      tags:
      - Robot Apps
      operationId: getRobotApp
      summary: Get one analytic script from a robot
      description: Get one analytic script from a robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotAppResponse'
              example:
                data:
                - id: 1
                  type: robot_apps
                  attributes:
                    comment: Try to hack the COM panel, maybe it will bypass the redundant port!
                    version: 1
                    created_at: '2019-03-21T16:25:00.367Z'
                    is_unicode: true
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/robots/{robot_id}/robot_apps:
    get:
      tags:
      - Robot Apps
      operationId: getRobotApps
      summary: List a robot's analytic scripts
      description: Get a list of a robot's analytic scripts.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotAppsResponse'
              example:
                data:
                - id: 1
                  type: robot_apps
                  attributes:
                    comment: Try to hack the COM panel, maybe it will bypass the redundant port!
                    version: 1
                    created_at: '2019-03-21T16:25:00.367Z'
                    is_unicode: true
                - id: 2
                  type: robot_apps
                  attributes:
                    comment: Use the open-source SQL firewall, then you can program the cross-platform pixel!
                    version: 2
                    created_at: '2019-03-21T16:25:00.590Z'
                    is_unicode: true
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Robot Apps
      operationId: createRobotApp
      summary: Create an analytic script
      description: Create a new analytic script for a robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      requestBody:
        description: The data required to create an analytic script.
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateRobotAppRequest'
      responses:
        '200':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotAppResponse'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: Unprocessable entity.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/RobotsError'
components:
  parameters:
    robotIdParam:
      in: path
      name: robot_id
      description: The ID of the robot.
      required: true
      schema:
        type: string
        example: 2
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    MissingRobotId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, robot_id, is missing.
  schemas:
    CreateRobotAppRequest:
      type: object
      description: The data associated with the resource.
      required:
      - file
      properties:
        code_page:
          type: integer
          example: 1250
          description: The character encoding of the uploaded .acl file.
        comment:
          type: string
          description: An informative statement in the version history of the script.
          example: Galvanize rocks!
        is_unicode:
          type: boolean
          description: Specifies whether the Robots Agent is working with Unicode character encoding of data.
          example: true
        file:
          type: string
          format: binary
          description: The .acl file containing the analytic script in binary format.
    GetRobotAppsResponse:
      type: object
      description: The data associated with the resource.
      properties:
        data:
          type: array
          description: The data associated with the resource.
          items:
            $ref: '#/components/schemas/RobotApp'
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    GetRobotAppResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/RobotApp'
    RobotsError:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                description: A HTTP response status code indicating an unprocessable entity.
                enum:
                - '422'
                example: '422'
              source:
                type: object
                properties:
                  pointer:
                    type: string
                    description: Indicates the specific source of the error.
                    example: /data/attributes/name
              title:
                type: string
                description: A title of the error.
                example: can't be blank
              detail:
                type: string
                description: A descriptive statement of the error.
                example: Name can't be blank
    RobotApp:
      type: object
      description: The data associated with the resource.
      required:
      - id
      - type
      - attributes
      properties:
        id:
          type: string
          description: The ID of the robot.
          example: 1
        type:
          type: string
          description: The classification of the object (`"robot_apps"`).
          example: robot_apps
        attributes:
          type: object
          description: The attributes associated with the resource.
          properties:
            comment:
              type: string
              description: An informative statement in the version history of the script.
              example: If we synthesize the application, we can get to the SSL firewall through the mobile XSS sensor!
            version:
              type: integer
              description: The script version number.
              example: 1
            created_at:
              type: string
              description: The date the robot was created.
              example: '2019-03-21T16:25:00.478Z'
            is_unicode:
              type: boolean
              description: Specifies whether the Robots Agent is working with Unicode character encoding of data.
              example: true
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
