openapi: 3.2.0
info:
  title: HighBond API Reference Robot Collaborators API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robot Collaborators
  x-displayName: Robot Collaborators
  description: Robot collaborators are users who have access to that particular robot.
paths:
  /orgs/{org_id}/robots/{robot_id}/collaborators:
    get:
      tags:
      - Robot Collaborators
      operationId: listRobotCollaborators
      summary: List Robot Collaborators
      description: Get a list of collaborators for a robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/robotQueryOffsetParam'
      - $ref: '#/components/parameters/robotQueryUsersPerPageParam'
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ListRobotCollaboratorsResponse'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  parameters:
    robotQueryUsersPerPageParam:
      name: usersPerPage
      in: query
      required: false
      description: Required number of records to read, start from 1
      schema:
        type: integer
        minimum: 1
        example: 2
    robotQueryOffsetParam:
      name: offset
      in: query
      required: false
      description: Required data records start position, start from 0
      schema:
        type: integer
        minimum: 0
        example: 1
    robotIdParam:
      in: path
      name: robot_id
      description: The ID of the robot.
      required: true
      schema:
        type: string
        example: 2
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  responses:
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
  schemas:
    ListRobotCollaboratorsResponse:
      type: object
      description: The data associated with the resource.
      properties:
        data:
          type: array
          description: The data associated with the resource
          items:
            type: object
            properties:
              id:
                type: number
                description: The user ID.
                example: 1
              type:
                type: string
                description: The classification of the object (`"collaborators"`).
                example: collaborators
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  username:
                    type: string
                    description: The username
                    example: user
                  email:
                    type: string
                    description: The email of the user.
                    example: user@diligent.com
                  role:
                    type: string
                    enum:
                    - reviewer
                    - editor
                    - owner
                    - readonly
                    - developer
                    description: The role a collaborator can have
                  admin:
                    type: boolean
                    description: Whether is admin or not
        total:
          type: number
          description: The total number of collaborators in the robot.
          example: 100
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
