openapi: 3.2.0
info:
  title: HighBond API Reference Robot Users API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robot Users
  x-displayName: Robot Users
  description: Users of the Robots module including some Robots-specific fields. Only Robots Admins can access this endpoint.
paths:
  /orgs/{org_id}/robots/users:
    get:
      tags:
      - Robot Users
      operationId: listRobotUsers
      summary: List Robot Users
      description: Get a list of users of the Robots module.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotUserCursorParam'
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ListRobotUsersResponse'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
  /orgs/{org_id}/robots/users/{user_id}:
    patch:
      tags:
      - Robot Users
      operationId: updateRobotUser
      summary: Update robot user
      description: Updates a robot user.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotUserIdParam'
      requestBody:
        description: The data required to update a robot user.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateRobotUserRequest'
            example:
              data:
                attributes:
                  robots_role: admin
                  agent_manager: true
      responses:
        '200':
          description: Success
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/UpdateRobotUserResponse'
        '400':
          $ref: '#/components/responses/SchemaValidationFailed'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
components:
  schemas:
    ListRobotUsersResponse:
      type: object
      description: The data associated with the resource.
      properties:
        data:
          type: object
          description: The data associated with the resource
          properties:
            users:
              type: array
              description: The list of users
              items:
                type: object
                properties:
                  id:
                    type: number
                    description: The user ID.
                    example: 1
                  type:
                    type: string
                    description: The classification of the object (`"users"`).
                    example: users
                  attributes:
                    type: object
                    description: The attributes associated with the resource.
                    properties:
                      uid:
                        type: string
                        description: The user UID
                        example: mkggNBvDK2Thnqp12J5H
                      name:
                        type: string
                        description: The user's name
                        example: Remy Miller
                      email:
                        type: string
                        description: The email of the user.
                        example: rpaquin@diligent.com
                      robots_role:
                        type: string
                        enum:
                        - admin
                        - user
                        description: The role of the user in the Robots module
                      agent_manager:
                        type: boolean
                        description: Whether the user can access the agent manager page
            next:
              type: string
              description: The full request url to fetch the next set of users
              example: https://apis.highbond.com/v1/orgs/15/robots/users?cursor=MTU=
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    UpdateRobotUserRequest:
      type: object
      properties:
        data:
          type: object
          properties:
            attributes:
              type: object
              properties:
                robots_role:
                  description: The role of the user in the Robots module
                  type: string
                  enum:
                  - admin
                  - user
                agent_manager:
                  type: boolean
                  description: Whether the user can access the agent manager page
              required:
              - robots_role
              - agent_manager
    UpdateRobotUserResponse:
      type: object
      description: The data associated with the resource.
      properties:
        data:
          type: object
          properties:
            id:
              type: number
              description: The user ID.
              example: 1
            type:
              type: string
              description: The classification of the object (`"users"`).
              example: users
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                uid:
                  type: string
                  description: The user UID
                  example: mkggNBvDK2Thnqp12J5H
                name:
                  type: string
                  description: The user's name
                  example: Remy Miller
                email:
                  type: string
                  description: The email of the user.
                  example: rpaquin@diligent.com
                robots_role:
                  type: string
                  enum:
                  - admin
                  - user
                  description: The role of the user in the Robots module
                agent_manager:
                  type: boolean
                  description: Whether the user can access the agent manager page
  responses:
    SchemaValidationFailed:
      description: Bad Request
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              title: Bad Request
              code: bad_request
              detail: params.org_id should NOT be shorter than 1 characters
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
  parameters:
    robotUserIdParam:
      in: path
      name: user_id
      description: The ID of the user.
      required: true
      schema:
        type: number
        example: 2
    robotUserCursorParam:
      in: query
      name: cursor
      description: Pagination cursor.
      required: false
      schema:
        type: string
        example: MTU=
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
