openapi: 3.2.0
info:
  title: HighBond API Reference Robot Files API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robot Files
  x-displayName: ACL robot related files
  description: 'Related files in an ACL robot are non-Analytics files such as Excel or delimited that can be used as input for scripts in the robot.


    Learn more about related files in ACL robots.'
paths:
  /orgs/{org_id}/robots/{robot_id}/robot_files:
    get:
      tags:
      - Robot Files
      operationId: getRobotFiles
      summary: List an ACL robot related files
      description: Get a list of related files for an ACL robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/robotEnvParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotFilesResponse'
              example:
              - id: 1
                type: robot_files
                attributes:
                  filename: Data_source.xls
                  created_at: '2019-03-21T16:25:00.367Z'
              - id: 2
                type: robot_files
                attributes:
                  filename: Data_input.sql
                  created_at: '2019-03-21T16:26:00.590Z'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    post:
      tags:
      - Robot Files
      operationId: createRobotFile
      summary: Upload an ACL robot related file
      description: Upload a related file to an ACL robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/robotEnvParam'
      requestBody:
        description: The data required to create a related file.
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateRobotFileRequest'
      responses:
        '200':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotFileResponse'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: Unprocessable entity.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/RobotsError'
  /orgs/{org_id}/robot_files/{id}:
    get:
      tags:
      - Robot Files
      operationId: getRobotFile
      summary: Get an ACL robot related file metadata
      description: Get the metadata for a related file by ACL robot ID.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotFileResponse'
              example:
                data:
                  id: 1
                  type: robot_files
                  attributes:
                    filename: Data_source.xls
                    created_at: '2019-03-21T16:25:00.367Z'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    delete:
      tags:
      - Robot Files
      operationId: deleteRobotFile
      summary: Delete an ACL robot related file
      description: Delete a related file by ACL robot ID.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: Deleted.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotFileResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/robot_files/{id}/download:
    get:
      tags:
      - Robot Files
      operationId: downloadFile
      summary: Download an ACL robot related file
      description: Download a related file by ACL robot ID.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: OK.
          content: {}
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  parameters:
    robotIdParam:
      in: path
      name: robot_id
      description: The ID of the robot.
      required: true
      schema:
        type: string
        example: 2
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    robotEnvParam:
      in: query
      name: env
      description: The environment of an analytic script.
      required: false
      schema:
        type: string
        enum:
        - development
        - production
        default: development
      example: production
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  schemas:
    RobotFile:
      type: object
      description: The data associated with the resource.
      required:
      - id
      - type
      - attributes
      properties:
        id:
          type: string
          description: The ID of the robot.
          example: 1
        type:
          type: string
          description: The classification of the object (`"robot_files"`).
          example: robot_files
        attributes:
          type: object
          description: The attributes associated with the resource.
          properties:
            created_at:
              type: string
              description: The date the robot was created.
              example: '2019-03-21T20:22:48.282Z'
            filename:
              type: string
              description: The name of the related file.
              example: Data_source.xls
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    CreateRobotFileRequest:
      type: object
      description: The data associated with the resource.
      required:
      - file
      properties:
        file:
          type: string
          format: binary
          description: A related file that you want to upload.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    GetRobotFileResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/RobotFile'
    RobotsError:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                description: A HTTP response status code indicating an unprocessable entity.
                enum:
                - '422'
                example: '422'
              source:
                type: object
                properties:
                  pointer:
                    type: string
                    description: Indicates the specific source of the error.
                    example: /data/attributes/name
              title:
                type: string
                description: A title of the error.
                example: can't be blank
              detail:
                type: string
                description: A descriptive statement of the error.
                example: Name can't be blank
    GetRobotFilesResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          description: The data associated with the resource.
          items:
            $ref: '#/components/schemas/RobotFile'
  responses:
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    Forbidden:
      description: Forbidden.
    BadCredentials:
      description: Bad credentials.
    MissingRobotId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, robot_id, is missing.
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
