openapi: 3.2.0
info:
  title: HighBond API Reference Scheduled Projects API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Scheduled Projects
  description: 'Get the list of projects a user is scheduled for, and the projects'' start and end dates.


    Learn more.'
paths:
  /orgs/{org_id}/users/:uid/scheduled_projects:
    get:
      tags:
      - Scheduled Projects
      operationId: getScheduledProjects
      summary: Get scheduled projects
      description: Get a list of scheduled projects for the user
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/uidPathParam'
      - $ref: '#/components/parameters/schedulerStartDateFilterParams'
      - $ref: '#/components/parameters/schedulerEndDateFilterParams'
      - $ref: '#/components/parameters/schedulerProjectStateFilterParams'
      - $ref: '#/components/parameters/pageSizeParam'
      - $ref: '#/components/parameters/pageNumberEncodedParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetScheduledProjectsResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  parameters:
    uidPathParam:
      name: uid
      description: The UID of the user.
      schema:
        type: string
        example: yvqdNCtv8TeM47WQtzau
      in: path
      required: true
    schedulerStartDateFilterParams:
      in: query
      name: filter[date][start]
      description: 'Requesting the API to filter results by start date.

        For more information, see <a href="#section/Making-requests">Making requests</a>

        '
      required: false
      schema:
        type: string
        example: '2021-04-28'
    pageSizeParam:
      in: query
      name: page[size]
      description: The number of items returned per page. Default is 50. Maximum is 100.
      required: false
      schema:
        type: string
        example: 25
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    pageNumberEncodedParam:
      in: query
      name: page[number]
      description: The Base64-encoded page number of records to return.
      required: false
      schema:
        type: string
        example: Mg==
    schedulerProjectStateFilterParams:
      in: query
      name: filter[scheduled_project_state]
      description: Requesting the API to filter results by scheduler project state. For more information, see <a href="#section/Making-requests">Making requests</a>
      required: false
      schema:
        type: string
        example: active
    schedulerEndDateFilterParams:
      in: query
      name: filter[date][end]
      description: 'Requesting the API to filter results by end date.

        For more information, see <a href="#section/Making-requests">Making requests</a>

        '
      required: false
      schema:
        type: string
        example: '2021-04-30'
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
  schemas:
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    GetScheduledProjectsResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The classification of the object (`"scheduled_projects"`).
                example: scheduled_projects
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  start_date:
                    type: string
                    description: The date specifying when the schedule for the project begins.
                    example: '2021-11-16'
                    format: date
                  end_date:
                    type: string
                    description: The date specifying when the schedule for the project ends.
                    example: '2021-12-01'
                    format: date
        links:
          type: object
          required:
          - next
          - prev
          properties:
            next:
              type:
              - string
              - 'null'
              description: Next page url
              example: /users/:uid/scheduled_projects?page[size]=5&page[number]=Mg==
            prev:
              type:
              - string
              - 'null'
              description: Previous page url
              example: null
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
