openapi: 3.2.0
info:
  title: HighBond API Reference Non-project time categories API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Non-project time categories
  description: 'Use non-project time categories to divide non-project time entries by categories.


    Learn more about non-project time categories.'
paths:
  /orgs/{org_id}/time_entry_categories:
    get:
      tags:
      - Non-project time categories
      operationId: getTimeEntryCategories
      summary: Get non-project time categories
      description: Get a list of all non-project time categories in your organization.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetTimeEntryCategoriesResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
      - Non-project time categories
      operationId: createTimeEntryCategory
      summary: Create a non-project time category
      description: 'Create a new non-project time category.


        Limitations:

        * There can be a maximum of 50 time categories per HighBond instance.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      requestBody:
        description: The data required to create a non-project time category.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateTimeEntryCategoryRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetTimeEntryCategoryResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/title
                  code: invalid_resource
                  detail: can't be blank
  /orgs/{org_id}/time_entry_categories/{id}:
    get:
      tags:
      - Non-project time categories
      operationId: getTimeEntryCategory
      summary: Get information about a non-project time category
      description: Get information about a non-project time category.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetTimeEntryCategoryResponse'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
      - Non-project time categories
      operationId: updateTimeEntryCategory
      summary: Update a non-project time category
      description: Make changes to a non-project time category.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      requestBody:
        description: The data required to update a non-project time category.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateTimeEntryCategoryRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetTimeEntryCategoryResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
    delete:
      tags:
      - Non-project time categories
      operationId: deleteTimeEntryCategory
      summary: Delete a non-project time category
      description: 'Permanently delete a non-project time category.


        > **Caution —**

        Deleting a non-project time category also permanently deletes any associated time entries.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  schemas:
    CreateTimeEntryCategoryRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"time_entry_categories"`).
              example: time_entry_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - name
              properties:
                name:
                  type: string
                  description: The name of the time entry category.
                  maxLength: 255
                  example: Administration
                position:
                  type: integer
                  format: int64
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                active:
                  type: boolean
                  description: The value that determines if the time entry category is active.
                  example: true
    GetTimeEntryCategoryResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"time_entry_categories"`).
              example: time_entry_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - name
              properties:
                name:
                  type: string
                  description: The name of the time entry category.
                  maxLength: 255
                  example: Administration
                position:
                  type: integer
                  format: int64
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                active:
                  type: boolean
                  description: The value that determines if the time entry category is active.
                  example: true
                created_at:
                  type: string
                  description: The timestamp identifying when the time entry category was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the time entry category was last updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    UpdateTimeEntryCategoryRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The classification of the object (`"time_entry_categories"`).
              example: time_entry_categories
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - name
              properties:
                name:
                  type: string
                  description: The name of the time entry category.
                  maxLength: 255
                  example: Administration
                position:
                  type: integer
                  format: int64
                  description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                    '
                  example: 1
                active:
                  type: boolean
                  description: The value that determines if the time entry category is active.
                  example: true
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    GetTimeEntryCategoriesResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            - relationships
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '1'
              type:
                type: string
                description: The classification of the object (`"time_entry_categories"`).
                example: time_entry_categories
              attributes:
                type: object
                description: The attributes associated with the resource.
                required:
                - name
                properties:
                  name:
                    type: string
                    description: The name of the time entry category.
                    maxLength: 255
                    example: Administration
                  position:
                    type: integer
                    format: int64
                    description: 'The value that determines the order in which it is displayed in the index action. `position` must be a value between `1` and `2147483647`.

                      '
                    example: 1
                  active:
                    type: boolean
                    description: The value that determines if the time entry category is active.
                    example: true
                  created_at:
                    type: string
                    description: The timestamp identifying when the time entry category was created.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
                  updated_at:
                    type: string
                    description: The timestamp identifying when the time entry category was last updated.
                    example: '2019-02-09T13:17:26Z'
                    format: date-time
          description: Array of time entries
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    NoContent:
      description: No content.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
  parameters:
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
