openapi: 3.2.0
info:
  title: HighBond API Reference Groups API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Groups
  description: 'Groups are a security feature in Launchpad that allow you to assign the same level of access to multiple users simultaneously.


    Learn more about adding and managing groups.'
paths:
  /orgs/{org_id}/groups:
    get:
      tags:
      - Groups
      operationId: getGroups
      summary: List groups in an instance
      description: Get a list of groups for a particular HighBond instance.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MultipleGroupsResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
      - Groups
      operationId: createGroup
      summary: Create a new group
      description: Add a group to a HighBond instance.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      requestBody:
        description: The data required to create a group.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateGroupRequest'
      responses:
        '201':
          description: Group created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetGroupResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
  /orgs/{org_id}/groups/{group_id}:
    get:
      tags:
      - Groups
      operationId: getGroup
      summary: Get group information
      description: Get basic information for a single group.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/groupIdPathParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetGroupResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
      - Groups
      operationId: updateGroup
      summary: Update group information
      description: Updates information for a single group.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/groupIdPathParam'
      requestBody:
        description: The data required to update a group.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateGroupRequest'
      responses:
        '200':
          description: Group updated.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetGroupResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '429':
          $ref: '#/components/responses/TooManyRequests'
components:
  schemas:
    GetGroupResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The group ID for the group.
              example: '10'
            type:
              type: string
              description: The classification of the object (`"groups"`) for API schema serialization purposes.
              example: groups
            attributes:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the group. The character limit is 255.
                  example: My Group
                purpose:
                  type: string
                  description: The purpose of the group. The character limit is 500.
                  example: To group users with the same access level together
                enabled:
                  type: boolean
                  description: This identifies whether the group is enabled for use.
                  example: true
                owners:
                  type: array
                  description: The users that are to be assigned as owners of the group.
                  items:
                    type: object
                    properties:
                      user_uid:
                        type: string
                        description: The user_uid
                  example:
                  - user_uid: P2tuGWyTWxCAQgTd1XKx
                members:
                  type: array
                  description: The users that are to be assigned as members of the group.
                  items:
                    type: object
                    properties:
                      user_uid:
                        type: string
                        description: The user_uid
                  example:
                  - user_uid: YhxzalsjfhauYna
                member_count:
                  type: number
                  description: The number of owners and members that the group has.
                  example: 2
    UpdateGroupRequest:
      type: object
      description: The data required to update a group.
      required:
      - data
      properties:
        data:
          type: object
          description: The data to update.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"groups"`) for API schema serialization purposes.
              example: groups
            attributes:
              type: object
              description: The attributes associated with the group.
              properties:
                name:
                  type: string
                  description: The name of the group. The character limit is 255.
                  example: My Group
                purpose:
                  type: string
                  description: The purpose of the group. The character limit is 500.
                  example: To group users with the same access level together
                enabled:
                  type: boolean
                  description: This identifies whether the group is enabled for use.
                  example: true
                owners:
                  type: array
                  description: The users that are to be assigned as owners of the group. If omitted, defaults to the user who initiates the request.
                  items:
                    type: object
                    properties:
                      user_uid:
                        type: string
                        description: The user_uid
                  example:
                  - user_uid: P2tuGWyTWxCAQgTd1XKx
                members:
                  type: array
                  description: The users that are to be assigned as members of the group. If a member is contained in the owners list, it will be ignored.
                  items:
                    type: object
                    properties:
                      user_uid:
                        type: string
                        description: The user_uid
                  example:
                  - user_uid: YhxzalsjfhauYna
    MultipleGroupsResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          description: An array of the groups within this HighBond instance.
          items:
            type: object
            required:
            - id
            - type
            - attributes
            properties:
              id:
                type: string
                description: The group ID for the group.
                example: '10'
              type:
                type: string
                description: The classification of the object (`"groups"`) for API schema serialization purposes.
                example: groups
              attributes:
                type: object
                properties:
                  name:
                    type: string
                    description: The name of the group. The character limit is 255.
                    example: My Group
                  purpose:
                    type: string
                    description: The purpose of the group. The character limit is 500.
                    example: To group users with the same access level together
                  enabled:
                    type: boolean
                    description: This identifies whether the group is enabled for use.
                    example: true
                  owners:
                    type: array
                    description: The users that are to be assigned as owners of the group.
                    items:
                      type: object
                      properties:
                        user_uid:
                          type: string
                          description: The user_uid
                    example:
                    - user_uid: P2tuGWyTWxCAQgTd1XKx
                  members:
                    type: array
                    description: The users that are to be assigned as members of the group.
                    items:
                      type: object
                      properties:
                        user_uid:
                          type: string
                          description: The user_uid
                    example:
                    - user_uid: YhxzalsjfhauYna
                  member_count:
                    type: number
                    description: The number of owners and members that the group has.
                    example: 2
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    CreateGroupRequest:
      type: object
      description: The data required to create a new group.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the new group.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"groups"`) for API schema serialization purposes.
              example: groups
            attributes:
              type: object
              description: The attributes associated with the new group.
              required:
              - name
              properties:
                name:
                  type: string
                  description: The name of the group. The character limit is 255.
                  example: My Group
                purpose:
                  type: string
                  description: The purpose of the group. The character limit is 500.
                  example: To group users with the same access level together
                owners:
                  type: array
                  description: The users that are to be assigned as owners of the group. If omitted, defaults to the user who initiates the request.
                  items:
                    type: object
                    properties:
                      user_uid:
                        type: string
                        description: The user_uid
                  example:
                  - user_uid: P2tuGWyTWxCAQgTd1XKx
                members:
                  type: array
                  description: The users that are to be assigned as members of the group. If a member is contained in the owners list, it will be ignored.
                  items:
                    type: object
                    properties:
                      user_uid:
                        type: string
                        description: The user_uid
                  example:
                  - user_uid: YhxzalsjfhauYna
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    TooManyRequests:
      description: Too many requests.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    BadCredentials:
      description: Bad credentials.
    UnprocessableEntity:
      description: Unprocessable entity.
  parameters:
    groupIdPathParam:
      name: group_id
      description: The ID of the group.
      schema:
        type: string
        example: 10
      in: path
      required: true
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
