openapi: 3.2.0
info:
  title: HighBond API Reference Robots Agents API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robots Agents
  description: 'A Robots Agent is the on-premise or cloud-based Robots component that uses the Analytics script engine to run scripts against data.


    Learn more about the Robots Agent.'
paths:
  /orgs/{org_id}/agents:
    get:
      tags:
      - Robots Agents
      operationId: getAgents
      summary: Get a list of Robots Agents
      description: Get a list of all of the Robots Agents available to your organization.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetAgentsResponse'
              example:
                data:
                - id: 1
                  type: agent
                  attributes:
                    is_unicode: true
                    type: cloud
                - id: 2
                  type: agent
                  attributes:
                    is_unicode: true
                    type: default
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  schemas:
    GetAgentsResponse:
      type: object
      description: The data associated with the resource.
      required:
      - id
      - type
      - attributes
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
                description: The ID of the robot.
                example: 1
              type:
                type: string
                description: The classification of the object.
                example: agent
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  agent_type:
                    type: string
                    enum:
                    - cloud
                    - default
                    - flow
                    description: The type of the agent. Can be `cloud`, `default`, or `flow`.
                    example: cloud
                  is_unicode:
                    type: boolean
                    description: If the agent is unicode or non-unicode.
                    example: cloud
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
  parameters:
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
