openapi: 3.2.0
info:
  title: HighBond API Reference Robot Script Versions API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robot Script Versions
  x-displayName: Robot script versions
  description: 'A version of a robot that includes the hcl script in json. You can upload new version of your hcl script to your highbond robot or workflow robot.


    Flow json includes python script, variables and system token user uid. See example of flow json in request body schema.'
paths:
  /orgs/{org_id}/robots/{robot_id}/versions/{version_id}:
    get:
      tags:
      - Robot Script Versions
      operationId: getRobotScriptVersion
      summary: Get script version of a robot
      description: Get version of a robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/versionIdParam'
      - $ref: '#/components/parameters/analyticsIncludeParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotScriptVersionResponse'
              example:
                data:
                  id: 1
                  type: robot_apps
                  attributes:
                    comment: Sample commit comment
                    version: 1
                  relationship:
                    analytics:
                      data:
                      - id: 2
                        type: analytic
                included:
                - id: 2
                  type: analytics
                  attributes:
                    name: Example Flow
                    raw:
                      edges: []
                      nodes:
                      - id: 7759ae53-a921-46b1-bc2f-49ac799e4882
                        kind: script
                        libraryNodeId: script-id
                        name: Script
                        config:
                          cells:
                          - id: 41e1aa1b-ab74-43bc-8d07-8f5f76590ab1
                            input: print('demo')↵↵print('second line of demo')
                          - id: f3d4eaae-45e4-499e-833e-fb0ae77abf59
                            input: 'print(''cell #2'')↵↵print(''another new line'')'
                      variables:
                      - id: a9e0bc9d-6dcc-4d2d-943c-fd1c795667c5
                        name: v_hb_token
                        type: system_user_id
                        value: '{the system user UID}'
                      - id: c41c0c69-bec7-464e-a7c9-effd0a321706
                        isTaskInput: false
                        name: v_character
                        type: character
                        value: My variable value
                      - id: 93674454-6a16-41a2-9e05-6f1f962d9a10
                        isTaskInput: true
                        name: v_password
                        taskInputLabel: My Password Task Param Label
                        type: password
                        value: ''
                      version: '2021-02-05'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/robots/{robot_id}/versions:
    post:
      tags:
      - Robot Script Versions
      operationId: createRobotScriptVersion
      summary: Create a robot script version
      description: Create a new robot app version and flow.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/analyticsIncludeParam'
      requestBody:
        description: The below data are `required` to create a script for highbond robots or workflow robots.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateRobotScriptVersionRequest'
      responses:
        '200':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetRobotScriptVersionResponse'
              example:
                data:
                  id: 1
                  type: robot_apps
                  attributes:
                    comment: Sample commit comment
                    version: 1
                  relationship:
                    analytics:
                      data:
                      - id: 2
                        type: analytic
                included:
                - id: 2
                  type: analytics
                  attributes:
                    name: Example Flow
                    raw:
                      edges: []
                      nodes:
                      - id: 7759ae53-a921-46b1-bc2f-49ac799e4882
                        kind: script
                        libraryNodeId: script-id
                        name: Script
                        config:
                          cells:
                          - id: 41e1aa1b-ab74-43bc-8d07-8f5f76590ab1
                            input: print('demo')↵↵print('second line of demo')
                          - id: f3d4eaae-45e4-499e-833e-fb0ae77abf59
                            input: 'print(''cell #2'')↵↵print(''another new line'')'
                      variables:
                      - id: a9e0bc9d-6dcc-4d2d-943c-fd1c795667c5
                        name: v_hb_token
                        type: system_user_id
                        value: '{the system user UID}'
                      - id: c41c0c69-bec7-464e-a7c9-effd0a321706
                        isTaskInput: false
                        name: v_character
                        type: character
                        value: My variable value
                      - id: 93674454-6a16-41a2-9e05-6f1f962d9a10
                        isTaskInput: true
                        name: v_password
                        taskInputLabel: My Password Task Param Label
                        type: password
                        value: ''
                      version: '2021-02-05'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: Unprocessable entity.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/RobotsError'
components:
  schemas:
    RobotScriptVersion:
      type: object
      description: The data associated with the resource.
      required:
      - id
      - type
      - attributes
      properties:
        id:
          type: string
          description: The ID of the script version.
          example: 1
        type:
          type: string
          description: The classification of the object (`"robot_apps"`).
          example: analytics
        attributes:
          type: object
          description: The attributes associated with the resource.
          properties:
            comment:
              type: string
              description: An informative statement in the version history.
              example: Example commit comment
            version:
              type: integer
              format: int64
              description: The version of the analytic
              example: 10
        relationships:
          type: object
          description: The resouces associated with this script version.
          properties:
            analytics:
              type: object
              description: List of flows associated with the script version.
              properties:
                data:
                  type: array
                  description: An array of analytic IDs associated with the script version.
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        description: The ID of the analytic.
                      type:
                        type: string
                        description: The classification of the object (`"analytic"`).
    GetRobotScriptVersionResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          $ref: '#/components/schemas/RobotScriptVersion'
        included:
          type: array
          description: All analytics related to the resource
          items:
            type: object
            properties:
              id:
                type: string
                description: The ID of the flow.
              type:
                type: string
                description: The classification of the object (`"analytics"`).
              attributes:
                type: object
                description: The attributes associated with the flow.
                properties:
                  name:
                    type: string
                    description: The name of the flow
                    example: Example Flow
                  raw:
                    type: object
                    description: Configuration object of the flow of a highbond robots or workflow robots.
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    CreateRobotScriptVersionRequest:
      type: object
      description: The data associated with the resource.
      properties:
        comment:
          type: string
          description: An informative statement in the version history.
          example: Example commit comment
        name:
          type: string
          description: Name of the flow
        raw:
          type: object
          description: "Configuration object of the flow of a highbond robots or workflow robots.  It contains user python scripts and variables set up in flow builder.  See example of the flow structure in the sample response.\n\nVersion in json is required.  Initial version of flow json is `version: '2021-02-05'`.\n\nenvironment is execution environments for user scripts. Each environment consists of a runtime (e.g. “python3.11”) and a list of packages (e.g. \"hcl==3.0.*\", \"boxsdk==3.9.2\")\n\nenvironment for a robot should have `runtime: \"python3.11\"` and `requirements` should include `hcl==3.0.*`. For HighBond Robot, additional packages can be included, however they should match the versions as given below:\n\n- Workflow Robot\n\n```\nenvironment: {\n  runtime: \"python3.11\",\n  requirements: [\n    \"hcl==3.0.*\"\n  ]\n}\n```\n\n- HighBond Robot\n\n```\nenvironment: {\n  runtime: \"python3.11\", \n  requirements: [\n    \"hcl==3.0.*\",\n    \"boxsdk==3.9.2\",\n    \"openpyxl==3.1.2\",\n    \"Jinja2==3.1.3\",\n    \"simple-salesforce==1.12.5\",\n    \"jira==3.8.0\"\n   ]\n }\n```\n\n>In case `environment` is missing or the packages (e.g `boxsdk` and others mentioned above) does not match the specified versions, API will throw an error.\n\n`id` in flow json needs to be unique.  Example shown are using uuidv4.\n\nNote: For the `hcl` requirement, specify a version that is a valid HCL library version number using this format: `major.minor.*` (For example, `hcl==3.0.*`) Use an asterisk (`*`) rather than a specific patch number. \n\n```\n{\n  version: '2021-02-05',\n  environment: {\n    runtime: \"python3.11\",\n    requirements: [\n      \"hcl==3.0.*\", \n      \"boxsdk==3.9.2\",\n      \"openpyxl==3.1.2\",\n      \"Jinja2==3.1.3\",\n      \"simple-salesforce==1.12.5\",\n      \"jira==3.8.0\"\n    ]\n  },\n  edges: []\n  nodes: [{\n    id: '7759ae53-a921-46b1-bc2f-49ac799e4882'\n    kind: 'script',\n    libraryNodeId: 'script-id',\n    name: 'Script',\n    config: {\n      cells: [\n        {\n          id: '41e1aa1b-ab74-43bc-8d07-8f5f76590ab1',\n          input: \"print('demo')↵↵print('second line of demo')\"\n        },\n        {\n          id: 'f3d4eaae-45e4-499e-833e-fb0ae77abf59',\n          input: \"print('cell #2')↵↵print('another new line')\"\n        }\n      ]\n    }\n  }]\n  variables: [\n    {\n      id: 'a9e0bc9d-6dcc-4d2d-943c-fd1c795667c5',\n      name: 'v_hb_token',\n      type: 'system_user_id',\n      value: '{the system user UID}'\n    },\n    {\n      id: 'c41c0c69-bec7-464e-a7c9-effd0a321706',\n      isTaskInput: false,\n      name: 'v_character',\n      type: 'character',\n      value: My variable value\n    },\n    {\n      id: '93674454-6a16-41a2-9e05-6f1f962d9a10',\n      isTaskInput: true,\n      name: 'v_password',\n      taskInputLabel: 'My Password Task Param Label',\n      type: 'password',\n      value: ''\n    }\n  ]\n}\n```\n"
    RobotsError:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                description: A HTTP response status code indicating an unprocessable entity.
                enum:
                - '422'
                example: '422'
              source:
                type: object
                properties:
                  pointer:
                    type: string
                    description: Indicates the specific source of the error.
                    example: /data/attributes/name
              title:
                type: string
                description: A title of the error.
                example: can't be blank
              detail:
                type: string
                description: A descriptive statement of the error.
                example: Name can't be blank
  parameters:
    robotIdParam:
      in: path
      name: robot_id
      description: The ID of the robot.
      required: true
      schema:
        type: string
        example: 2
    versionIdParam:
      in: path
      name: version_id
      description: The ID of the version.
      required: true
      schema:
        type: string
        example: 2
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    analyticsIncludeParam:
      in: query
      name: include
      description: If specified, the associated analytic scripts will be included in the `included` object
      required: false
      schema:
        type: string
        enum:
        - analytics
      example: analytics
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    MissingRobotId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, robot_id, is missing.
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
