openapi: 3.2.0
info:
  title: HighBond API Reference Mitigations API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Mitigations
  description: '> **Note —**

    Only controls in projects that have an `"active"` state can be accessed using the API.'
paths:
  /orgs/{org_id}/mitigations:
    post:
      tags:
      - Mitigations
      operationId: createMitigation
      summary: Create a mitigation
      description: 'Create a new mitigation.


        Limitations:

        * There can be a maximum of 200,000 mitigations per project or framework.

        * You cannot create a mitigation if the objective it belongs to has been checked out using

        Offline Projects or the

        HighBond iPad app.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      requestBody:
        description: The data required to create a mitigation.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateMitigationRequest'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetMitigationResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/weight
                  code: invalid_resource
                  detail: must be less than or equal to 100
  /orgs/{org_id}/mitigations/{id}:
    get:
      tags:
      - Mitigations
      operationId: getMitigation
      summary: Get a mitigation
      description: Get information about a mitigation.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetMitigationResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
    patch:
      tags:
      - Mitigations
      operationId: updateMitigation
      summary: Update a mitigation
      description: 'Make changes to a mitigation.


        Limitations:

        * You cannot update the mitigation if the objective it belongs to has been checked out using

        Offline Projects or the

        HighBond iPad app.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      requestBody:
        description: The data required to update a mitigation.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateMitigationRequest'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/GetMitigationResponse'
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/weight
                  code: invalid_resource
                  detail: must be less than or equal to 100
    delete:
      tags:
      - Mitigations
      operationId: deleteMitigation
      summary: Delete a mitigation
      description: 'Permanently delete a mitigation.


        Limitations:

        * You cannot delete the mitigation if the objective it belongs to has been checked out using

        Offline Projects or the

        HighBond iPad app.


        > **Caution —**

        Deleting a mitigation is permanent. Once deleted, you cannot access or restore the mitigation.'
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
components:
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    NoContent:
      description: No content.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
  parameters:
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  schemas:
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    GetMitigationResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          - relationships
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of mitigation (`"mitigations"`).
              example: mitigations
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - weight
              properties:
                weight:
                  type: integer
                  description: the weight of mitigation. Must be > 0 and less than 100.
                  minimum: 0
                  maximum: 100
                  example: 99
                created_at:
                  type: string
                  description: The timestamp identifying when the mitigation was created.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
                updated_at:
                  type: string
                  description: The timestamp identifying when the mitigation was last updated.
                  example: '2019-02-09T13:17:26Z'
                  format: date-time
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - risk
              - control
              properties:
                control:
                  type: object
                  description: 'Each mitigation has an associated control.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the control.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"controls"`).
                          example: controls
                risk:
                  type: object
                  description: 'Each mitigation has an associated risk.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the risk.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"risks"`).
                          example: risks
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    CreateMitigationRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          - relationships
          properties:
            type:
              type: string
              description: The type of mitigation (`"mitigations"`).
              example: mitigations
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - weight
              properties:
                weight:
                  type: integer
                  description: the weight of mitigation. Must be > 0 and less than 100.
                  minimum: 0
                  maximum: 100
                  example: 99
            relationships:
              type: object
              description: The relationships associated with the resource.
              required:
              - risk
              - control
              properties:
                control:
                  type: object
                  description: 'Each mitigation has an associated control.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the control.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"controls"`).
                          example: controls
                risk:
                  type: object
                  description: 'Each mitigation has an associated risk.

                    '
                  required:
                  - data
                  properties:
                    data:
                      type: object
                      description: The data associated with the resource.
                      required:
                      - id
                      - type
                      properties:
                        id:
                          type: string
                          description: The ID of the risk.
                          example: '1'
                        type:
                          type: string
                          description: The classification of the object (`"risks"`).
                          example: risks
    UpdateMitigationRequest:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the requested resource.
              example: '1'
            type:
              type: string
              description: The type of mitigation (`"mitigations"`).
              example: mitigations
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - weight
              properties:
                weight:
                  type: integer
                  description: the weight of mitigation. Must be > 0 and less than 100.
                  minimum: 0
                  maximum: 100
                  example: 99
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
