openapi: 3.2.0
info:
  title: HighBond API Reference Workflow Groups API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Workflow Groups
  description: 'Workflow groups are a permissions feature that allow you to define users as members of a specific group. A single user can belong to multiple workflow groups.


    Learn more about workflow groups.'
paths:
  /orgs/{org_id}/workflow_groups:
    get:
      tags:
      - Workflow Groups
      operationId: getWorkflowGroups
      summary: Get a list of all workflow groups
      description: Get a list of all the workflow groups within the Results app of an organization.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MultiWorkflowGroupsResponse'
              example:
                data:
                - id: '22'
                  type: workflow_groups
                  attributes:
                    name: group 2
                    users: []
                - id: '21'
                  type: workflow_groups
                  attributes:
                    name: group 1
                    users:
                    - id: 1
                      name: bob
                      email: bob@example.com
                    - id: 2
                      name: alice
                      email: alice@exmaple.com
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
  /orgs/{org_id}/workflow_groups/{workflow_group_id}/users:
    post:
      tags:
      - Workflow Groups
      operationId: createWorkflowGroup
      summary: Add user to a workflow group
      description: Add users to the workflow groups that streamlines user assignment.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/workflowGroupIdParam'
      requestBody:
        description: The data required to add a user to a workflow group.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/AddUserToWorkflowGroupPayload'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/AddUserToWorkflowGroupResponse'
        '400':
          $ref: '#/components/responses/ResourceTypeMismatch'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/AddUserToWorkflowGroupErrorResponse'
  /orgs/{org_id}/workflow_groups/{workflow_group_id}/users/{user_id}:
    delete:
      tags:
      - Workflow Groups
      operationId: deleteWorkflowGroup
      summary: Remove a user from workflow group
      description: Remove users from the workflow groups for efficient user assignment.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/workflowGroupIdParam'
      - $ref: '#/components/parameters/workflowGroupUserIdParam'
      responses:
        '204':
          description: No content.
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/DeleteWorkflowGroupErrorResponse'
components:
  parameters:
    workflowGroupIdParam:
      in: path
      name: workflow_group_id
      description: The ID of the workflow group.
      required: true
      schema:
        type: integer
        example: 101
    workflowGroupUserIdParam:
      in: path
      name: user_id
      description: The ID of the user.
      required: true
      schema:
        type: integer
        example: 300
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    Forbidden:
      description: Forbidden.
    ResourceTypeMismatch:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_type_mismatch
              title: Resource type mismatch
              detail: 'The requested data type, a-bad-type, is incompatible with the endpoint.

                '
    BadCredentials:
      description: Bad credentials.
  schemas:
    AddUserToWorkflowGroupResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: number
              description: The ID of the user added to workflow group.
              example: 301
            type:
              type: string
              description: The classification of the object (`"users"`).
              example: users
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                username:
                  type: string
                  description: The username of the user.
                  example: bob
                email:
                  type: string
                  description: The email of the user.
                  example: bob@yahoo.com
                admin:
                  type: boolean
                  description: Whether the user is a Results admin.
                  example: true
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    MultiWorkflowGroupsResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: array
          description: The data associated with the resource.
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            properties:
              id:
                type: string
                description: The ID of the requested resource.
                example: '21'
              type:
                type: string
                description: The classification of the object (`"workflow_groups"`).
                example: workflow_groups
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  name:
                    type: string
                    description: The name of the workflow group.
                    maxLength: 255
                    example: Group 1
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The ID of the user
                          example: '1'
                        name:
                          type: string
                          description: The name of the user
                          example: bob
                        email:
                          type: string
                          description: The user's email address
                          example: bob@example.com
                    example:
                    - id: 1
                      name: bob
                      email: bob@example.com
                    - id: 2
                      name: alice
                      email: alice@example.com
    DeleteWorkflowGroupErrorResponse:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                description: A HTTP response status text indicating an error.
                example: '422'
              code:
                type: string
                description: A HTTP status code indicating an error.
                example: unprocessable_entity
              detail:
                type: string
                description: A descriptive statement of the error.
                example: User is not assigned to the workflow group.
    AddUserToWorkflowGroupErrorResponse:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            type: object
            properties:
              status:
                type: string
                description: A HTTP response status text indicating an error.
                example: '422'
              code:
                type: string
                description: A HTTP status code indicating an error.
                example: unprocessable_entity
              detail:
                type: string
                description: A descriptive statement of the error.
                example: User cannot be found.
    AddUserToWorkflowGroupPayload:
      type: object
      description: The data required to add a user to a workflow group.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              description: The classification of the object (`"users"`).
              type: string
              example: users
            attributes:
              type: object
              description: The attributes associated with the resource.
              required:
              - user_id
              properties:
                user_id:
                  type: string
                  description: The ID of the user to add to the workflow group.
                  example: '30'
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
