openapi: 3.2.0
info:
  title: HighBond API Reference Record statuses API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Record statuses
  x-displayName: Record statuses
  description: A dictionary of table record statuses
paths:
  /orgs/{org_id}/record_statuses/{id}:
    get:
      tags:
      - Record statuses
      operationId: getRecordStatus
      summary: Get a record status
      description: Get data for the record status with the specified id
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/SingleRecordStatusResponse'
              example:
                data:
                  id: 20
                  type: record_statuses
                  attributes:
                    name: Open
                    active: true
        '400':
          $ref: '#/components/responses/MissingResourceId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    patch:
      tags:
      - Record statuses
      operationId: updateRecordStatus
      summary: Update a record status
      description: Make changes to a record status, like renaming it or activating/deactivating it.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      requestBody:
        description: The data required to update a record status.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/UpdateRecordStatusPayload'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/SingleRecordStatusResponse'
        '400':
          $ref: '#/components/responses/ResourceIdConflict'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: A status with this name already exists.
    delete:
      tags:
      - Record statuses
      operationId: deleteRecordStatus
      summary: Delete a record status
      description: Delete the record status from the organization
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/resourceIdParam'
      responses:
        '202':
          description: Accepted
        '400':
          $ref: '#/components/responses/ResourceIdConflict'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
  /orgs/{org_id}/record_statuses:
    get:
      tags:
      - Record statuses
      operationId: getRecordStatuses
      summary: Get record statuses
      description: Get data for each record status of an organization
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      responses:
        '200':
          description: OK.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/MultiRecordStatusResponse'
              example:
                data:
                - id: '1'
                  type: record_statuses
                  attributes:
                    name: Open
                    active: true
                - id: '2'
                  type: record_statuses
                  attributes:
                    name: Under review
                    active: true
                - id: '3'
                  type: record_statuses
                  attributes:
                    name: Status 3
                    active: false
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
      - Record statuses
      operationId: createRecordStatus
      summary: Create a record status
      description: Create a new record status
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      requestBody:
        description: The data required to create a record status.
        required: true
        content:
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/CreateRecordStatusPayload'
      responses:
        '201':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/SingleRecordStatusResponse'
        '400':
          $ref: '#/components/responses/MissingOrgId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '415':
          $ref: '#/components/responses/NotJsonapiMediaType'
        '422':
          description: 'Unprocessable entity.

            '
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Errors'
              example:
                errors:
                - status: 422
                  source:
                    pointer: /data/attributes/name
                  code: invalid_resource
                  detail: can't be blank
components:
  schemas:
    MultiRecordStatusResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: array
          items:
            type: object
            description: The data associated with the resource.
            required:
            - id
            - type
            - attributes
            properties:
              id:
                type: integer
                description: The ID of the record status
                example: '20'
              type:
                type: string
                description: The classification of the object (`"record_statuses"`)
                example: record_statuses
              attributes:
                type: object
                description: The attributes associated with the resource.
                properties:
                  name:
                    type: string
                    description: The name of the record status.
                    maxLength: 255
                    example: Open
                  active:
                    type: boolean
                    description: Indicates whether the record status is active or not.
                    example: true
                    default: true
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    SingleRecordStatusResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: integer
              description: The ID of the record status
              example: '20'
            type:
              type: string
              description: The classification of the object (`"record_statuses"`)
              example: record_statuses
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                name:
                  type: string
                  description: The name of the record status.
                  maxLength: 255
                  example: Open
                active:
                  type: boolean
                  description: Indicates whether the record status is active or not.
                  example: true
                  default: true
    UpdateRecordStatusPayload:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the record status that needs to be changed.
              example: '20'
            type:
              type: string
              description: The classification of the object (`"record_statuses"`).
              example: record_statuses
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                name:
                  type: string
                  description: The name of the record status.
                  maxLength: 255
                  example: Open
                active:
                  type: boolean
                  description: Indicates whether the record status is active or not.
                  example: true
                  default: true
                position:
                  type: integer
                  description: Specifies the order of statuses.
                  example: 5
    CreateRecordStatusPayload:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - type
          - attributes
          properties:
            type:
              type: string
              description: The classification of the object (`"record_statuses"`).
              example: record_statuses
            attributes:
              required:
              - name
              type: object
              description: The attributes associated with the resource.
              properties:
                name:
                  type: string
                  description: The name of the record status.
                  maxLength: 255
                  example: Open
                active:
                  type: boolean
                  description: Indicates whether the record status is active or not.
                  example: true
                  default: true
                position:
                  type: integer
                  description: Specifies the order of statuses.
                  example: 5
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    MissingOrgId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, org_id, is missing.
    NotJsonapiMediaType:
      description: Unsupported media type.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 415
              code: unsupported_media_type
              title: Unsupported media type
              detail: 'The endpoint supports only the application/vnd.api+json Content-Type. This request specified application/json.

                '
    ResourceIdConflict:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: resource_id_conflict
              title: Resource ID conflict
              detail: 'The id specified in the request body, 1, conflicts with

                the id specified in the path, 101.

                '
    Forbidden:
      description: Forbidden.
    BadCredentials:
      description: Bad credentials.
    MissingResourceId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, id, is missing.
  parameters:
    resourceIdParam:
      in: path
      name: id
      description: The ID of the requested resource.
      required: true
      schema:
        type: string
        example: 9999
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
