openapi: 3.2.0
info:
  title: HighBond API Reference Robot Working Files API
  version: 1.1.0
  description: Welcome to the API documentation for HighBond.
  x-logo:
    url: ./assets/logo.png
    altText: HighBond Logo
servers:
- url: '{protocol}://{server}/v1'
  variables:
    protocol:
      default: https
    server:
      default: apis-us.highbond.com
      enum:
      - apis-us.highbond.com
      - apis-ca.highbond.com
      - apis-eu.highbond.com
      - apis-ap.highbond.com
      - apis-au.highbond.com
      - apis-af.highbond.com
      - apis-sa.highbond.com
      - apis-jp.highbond.com
security:
- bearerToken: []
tags:
- name: Robot Working Files
  x-displayName: HighBond/Workflow robot working files
  description: Working files in a HighBond robot or a Workflow robot are files such as Excel or CSV that can be used as input for scripts in the robot.
paths:
  /orgs/{org_id}/robots/{robot_id}/working_files:
    get:
      tags:
      - Robot Working Files
      operationId: downloadRobotWorkingFile
      summary: Download a HighBond/Workflow robot working file
      description: Download a working file to a HighBond or Workflow robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/robotEnvParam'
      - $ref: '#/components/parameters/robotFileNameParam'
      responses:
        '200':
          description: The download url and the expiration date of that url.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/DownloadRobotWorkingFileResponse'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    post:
      tags:
      - Robot Working Files
      operationId: createRobotWorkingFile
      summary: Upload a HighBond/Workflow robot working file
      description: Upload a working file to a HighBond or Workflow robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/robotEnvParam'
      - in: query
        name: overwrite
        description: Overwrite an existing working file with the same name.
        required: false
        schema:
          type: boolean
          default: false
      requestBody:
        description: The data required to upload a working file.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRobotWorkingFileRequest'
      responses:
        '200':
          description: Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CreateRobotWorkingFileResponse'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      tags:
      - Robot Working Files
      operationId: deleteRobotWorkingFile
      summary: Delete a HighBond/Workflow robot working file
      description: Delete a working file to a HighBond or Workflow robot.
      parameters:
      - $ref: '#/components/parameters/orgIdParam'
      - $ref: '#/components/parameters/robotIdParam'
      - $ref: '#/components/parameters/robotEnvParam'
      - $ref: '#/components/parameters/robotFileNameParam'
      responses:
        '200':
          description: The name of the deleted file.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/DeleteRobotWorkingFileResponse'
        '400':
          $ref: '#/components/responses/MissingRobotId'
        '401':
          $ref: '#/components/responses/BadCredentials'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    DeleteRobotWorkingFileResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource
          properties:
            id:
              type: string
              description: The ID of the file.
              example: Data_source.xls
            type:
              type: string
              description: The classification of the object (`"robot_files"`).
              example: robot_files
    CreateRobotWorkingFileResponse:
      type: object
      description: The data associated with the resource.
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          required:
          - id
          - type
          - attributes
          properties:
            id:
              type: string
              description: The ID of the robot.
              example: Data_source.xls
            type:
              type: string
              description: The classification of the object (`"robot_files"`).
              example: robot_files
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                uploadUrl:
                  type: string
                  description: The url to upload the file to.
                  example: https://acl-highbond-drive-us2-main-s1.s3.us-west-2.amazonaws.com/1000223/robots/dev/48586/working_files/Data_source.xls
                expirationDate:
                  type: string
                  description: The date the url expires.
                  example: '2019-03-21T20:22:48.282Z'
    Error:
      type: object
      required:
      - status
      properties:
        status:
          type: string
          description: The HTTP status code.
        source:
          type: object
          description: Indicates which part of the request document caused the error.
          required:
          - pointer
          properties:
            pointer:
              type: string
              description: 'A JSON Pointer <a href="https://tools.ietf.org/html/rfc6901" target="_blank">(RFC6901)</a> to the associated entity

                in the request document.

                '
        code:
          type: string
          description: Application-specific error code, expressed as a string value.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
    CreateRobotWorkingFileRequest:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          properties:
            type:
              type: string
              description: The classification of the object (`"robot_files"`).
              example: robot_files
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                filename:
                  type: string
                  description: The name of the file.
                  example: Data_source.xls
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    DownloadRobotWorkingFileResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          description: The data associated with the resource.
          properties:
            id:
              type: string
              description: The ID of the file.
              example: Data_source.xls
            type:
              type: string
              description: The classification of the object (`"robot_files"`).
              example: robot_files
            attributes:
              type: object
              description: The attributes associated with the resource.
              properties:
                downloadUrl:
                  type: string
                  description: The url to download the file.
                  example: https://acl-highbond-drive-us2-main-s1.s3.us-west-2.amazonaws.com/1000223/robots/dev/48586/working_files/Data_source.xls
                expirationDate:
                  type: string
                  description: The date the url expires.
                  example: '2019-03-21T20:22:48.282Z'
  parameters:
    robotIdParam:
      in: path
      name: robot_id
      description: The ID of the robot.
      required: true
      schema:
        type: string
        example: 2
    robotEnvParam:
      in: query
      name: env
      description: The environment of an analytic script.
      required: false
      schema:
        type: string
        enum:
        - development
        - production
        default: development
      example: production
    orgIdParam:
      in: path
      name: org_id
      description: The ID of the HighBond instance.
      required: true
      schema:
        type: string
        example: 1
    robotFileNameParam:
      in: query
      name: filename
      description: Filename id.
      required: true
      schema:
        type: string
        example: filename.txt
  responses:
    NotFound:
      description: Not found.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: '404'
              title: Not Found
              detail: The requested resource does not exist.
    BadCredentials:
      description: Bad credentials.
    Forbidden:
      description: Forbidden.
    MissingRobotId:
      description: Bad request.
      content:
        application/vnd.api+json:
          schema:
            $ref: '#/components/schemas/Errors'
          example:
            errors:
            - status: 400
              code: parameter_missing
              title: Parameter missing
              detail: The required parameter, robot_id, is missing.
  securitySchemes:
    bearerToken:
      description: 'HighBond offers the industry-standard OAuth 2.0 flow for connecting to the HighBond platform. OAuth 2.0 provides a

        safe and secure way to access data, while protecting your account credentials.

        '
      type: http
      scheme: bearer
      bearerFormat: oauth2
x-tagGroups:
- name: Core resources
  tags:
  - Robots Agents
  - Robots
  - Robot Tasks
  - Robot Jobs
  - Robot Apps
  - Robot Script Versions
  - Robot Activations
  - Robot Files
  - Robot Working Files
  - Robot Collaborators
  - Robots Folders Collaborators
  - Robot Users
  - Robots Folders
  - Storyboards
  - Collections
  - Questionnaires
  - Analyses
  - Surveys
  - Event Reports
  - Tables
  - Table columns
  - Records
  - Record columns
  - Record statuses
  - Interpretations
  - Metrics
  - Workflow Groups
  - Results Users
  - Results Triggers
  - Project types
  - Custom attributes
  - Request item statuses
  - Projects
  - Projects Admin
  - Planning files
  - Results files
  - Objectives
  - Narratives
  - Risks
  - Controls
  - Control performance schedules
  - Mitigations
  - Control test plans
  - Control tests
  - Attachments
  - Walkthroughs
  - Issues
  - Actions
  - Collaborators
  - Request Items
  - To-dos
  - Sign-offs
  - Entities
  - Scheduler Filters
  - Frameworks
  - Handlers
  - Workflows in Asset Inventory/Asset Manager
  - Asset types
  - Asset record types
  - Attribute types
  - Assets
  - Asset Relationships
  - Asset records
  - Asset Record Relationships
  - Events
  - Template Toolkits
  - Toolkits
  - Roles
  - Role Deletion
  - Compliance Maps
  - Time entries
  - Non-project time categories
  - Timesheets
  - Importer
  - System Users
  - Organizations
  - Impact Reports
  - Activities
  - Users
  - Groups
  - Scheduled Users
  - Scheduled Projects
  - Scheduled Hours
  - Extract
  - Strategy
